### ISSUE TITLE
Make Tracking Events Configurable

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-mixpanel#10]
Add a config file to allow disabling of tracking of any of the events being tracked out of the box.

**Comment by alektrich** [comment]
I agree. This would be really helpful. I have people object duplication issues when setting my own "user started" tracking, for example, that sets email as a distinct ID. 
I hope it's feasible to implement that soon. Thank you!

**Comment by IvanJov** [comment]
I agree with you guys. I think that this feature can useful. I will try to implement it and then @mikebronner can review it and accept pull request if everything is ok. What do you think?

**Comment by mikebronner** [comment]
Thanks guys. Really this should only be a configuration boolean, which then is looked at in the event listeners. Thanks for the feedback, I will see what I can do over the next few days on this. :)

**Comment by IvanJov** [comment]
Thanks @mikebronner !

**Comment by alektrich** [comment]
@IvanJov @mikebronner Great! :)

**Comment by mikebronner** [comment]
This is now implemented in 0.5.3. See README step #3. Please let me know how this works for you guys. :)
