### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by AlexLightning** [GeneaLabs/laravel-mixpanel#104]
Hi!

Can you add Laravel 9 support? When I try to install it says:

` Problem 1
    - Root composer.json requires genealabs/laravel-mixpanel ^0.11.1 -> satisfiable by genealabs/laravel-mixpanel[0.11.1].
    - genealabs/laravel-mixpanel 0.11.1 requires illuminate/auth ^8.0 -> found illuminate/auth[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by mikebronner** [comment]
Thanks for the prompt. Will get that done right now.
