### ISSUE TITLE
Disable CSRF, unsure about how to do it in L5.2

### ISSUE THREAD

**Issue by simabo** [GeneaLabs/laravel-mixpanel#12]
Hi Mike,

A quick question: the readme states (point 5 in Configuration) that we should update a Middleware to bypass the CSRF checking for Stripe.

It looks like the file in question has changed in Laravel 5.2, see it [here](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/VerifyCsrfToken.php) 

I'm unsure about how to proceed: should I copy in this class the base "handle" function (visible in the parent class BaseVerifier) and amend it?

Thanks for sharing this package!

**Comment by simabo** [comment]
It might be as simple as adding 'genealabs/laravel-mixpanel/*' to the $except protected array... If you can confirm, then the readme probably should be updated.

**Comment by mikebronner** [comment]
You're exactly right! :) I just checked a Laravel 5.2 project I have it in, and just adding it to the $except variable (in `app/HTTP/Middleware/VerifiCsrfToken.php`) is the way to go:

```php
    protected $except = [
        'genealabs/laravel-mixpanel/*',
        'stripe/webhook',
    ];
```

**Comment by mikebronner** [comment]
Updated the readme as well. :)

**Comment by simabo** [comment]
Wow, impressive :)
Thanks again, much appreciated!

Having zillions of web services to connect to my app, your package is more than welcome and saves me a huge amount of time. I hope to return the favor to the community pretty soon.

**Comment by mikebronner** [comment]
Nice, glad to hear it!!
