### ISSUE TITLE
Enable Queueing of Events

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [GeneaLabs/laravel-mixpanel#15]
I'd like to disable some or all events to be sent automatically. The reason is that I'd like to send them via queued job. The other solution would be to make them queueable.

**Comment by KonstantinKolodnitsky** [comment]
Ah, sorry, my fault.

'mixpanel' => [
      'token' => env('MIXPANEL_TOKEN'),
      'enable-default-tracking' => false|true,
    ],

**Comment by mikebronner** [comment]
I like the idea of making them quable, if necessary. I say "if necessary", because I think by default Mixpanel reports the events async, so it shouldn't affect performantce. I will verify that, and look into making events quable. 

Thanks for the suggestion! :)

**Comment by KonstantinKolodnitsky** [comment]
Yes, I think it's a good option, but I'd create another ticket directly related to the question.

The solution seems quite easy. Just add `implement ShouldQueue` to event listeners. But it'll make them queue always. It might break if queueing is not configured. Have a look on 'Manually Accessing The Queue' part of https://laravel.com/docs/5.2/events#queued-event-listeners.

And thanks for the plugin!

**Comment by mikebronner** [comment]
Implementing queuing is not an issue. However, I would like to avoid implementing queuing just for the sake of it, if there is no real problem. I'm just curious if this is "pre-mature optimization" -- trying to put something on the queue in anticipation of it slowing down the app, before there is any evidence of it actually causing problems.

I use it with most of my projects, and haven't seen any issue that would be solved by queuing. If you could provide some feedback in this regard, that would be great. :)

**Comment by KonstantinKolodnitsky** [comment]
Unfortunately it's the first time I use MixPanel at all so I don't have any experience with it. The client's requirement is to use queue. Can't compare. Sorry for that.

**Comment by mikebronner** [comment]
I followed up withmixpanel, and indeed the events are not async. I will look into making them queueable, since that is indeed a valid concern.

Thanks for bearing with me and discussing it :)

**Comment by KonstantinKolodnitsky** [comment]
You are welcome.
If you'd like me to make speed comparison or other tests let me know.

**Comment by mikebronner** [comment]
Looking into this some more, I'm not sure there would be any benefit to queueing them. While by default Mixpanel uses Guzzle (as the email response from Mixpanel indicates), I have implemented it to use a socket connection (which I realized after reviewing the code yesterday evening), which turns out to be async precisely because I ran into blocking issues with multiple simultaneous CURL processes, as well as latency.

This should satisfy your business requirements? (Queueing just for the sake of queueing is not enough reason to implement the change.)

**Comment by KonstantinKolodnitsky** [comment]
Absolutely agree with you. Great job!

**Comment by mikebronner** [comment]
Re-opening this, as I found a valid use-case for it:
- if implementing queues other than sync, it will allow the event to be retried until mixpanel connection is re-established.

**Comment by mikebronner** [comment]
Refactoring everything to event listeners for now. This will easily allow enabling of queueing if a good solution is found.

**Comment by mikebronner** [comment]
This really isn't a concern at this point. Closing for now.
