### ISSUE TITLE
Use of Route::controller invalid in Laravel 5.3

### ISSUE THREAD

**Issue by mglinski** [GeneaLabs/laravel-mixpanel#17]
![](https://cl.ly/162F2r0t1h3i/Image%202016-08-24%20at%2011.55.43%20AM.png)

See: https://github.com/GeneaLabs/laravel-mixpanel/blob/master/src/Http/routes.php#L6

This routing method was deprecated in v5.2 and is now removed in v5.3.

**Comment by mikebronner** [comment]
Thanks for this list! Upgrading to L5.3 was on my todo. :)

**Comment by mglinski** [comment]
I made the change and put up a PR for it.

**Comment by mikebronner** [comment]
Awesome! :) Thanks

**Comment by mglinski** [comment]
Im not sure what your release timeline is for 0.5 but this is currently preventing my automated deployments from validating. Can this be fast tracked as a patch release? It should be fully backwards conpatable all the way back to 5.0.

**Comment by mikebronner** [comment]
It wil be backward compatible to L5.1 (LTS) for sure. I can't guarantee L5.0. Timeline is looking like this weekend.

**Comment by mikebronner** [comment]
You should now be able to reference this commit in your composer.json, so your builds will start passing again (just until I get 0.6 released):

```yml
"genealabs/laravel-mixpanele": "dev-master#dfc33409be4dd6360db48fc397fec07e33559626"
```
