### ISSUE TITLE
Laravel 5.3. core events are now objects

### ISSUE THREAD

**Issue by Dartanjan** [GeneaLabs/laravel-mixpanel#28]
I think you've seen this (looking at your code), but some events are no longer firing because they need to be referenced as objects, e.g. `Illuminate\Routing\Events\RouteMatched` instead of `router.matched`. All other core events in your code as well.

Exact commit on LR here: https://github.com/laravel/framework/commit/41599959d45016f0280d986f758d414fbee81863

This is on `0.6.0-RC@dev`, not sure about earlier versions.

**Comment by mikebronner** [comment]
@Dartanjan Thanks! I haven't had much time to look into this over the holidays. Will make an update and release 0.6 with that fix. I suspected something might be up. :)

**Comment by Dartanjan** [comment]
@mikebronner awesome, thanks!

**Comment by mikebronner** [comment]
Working on this now... sorry for the delay.

**Comment by mikebronner** [comment]
@Dartanjan can you check if this is still an issue with the latest dev-master? I don't see anywhere other than LaravelMixpanelEventHandler I am listening for events.

**Comment by mikebronner** [comment]
No response and working in L5.4. Closing for now, please re-open this issue if this is still a problem. :)
