### ISSUE TITLE
Identical events firing twice?

### ISSUE THREAD

**Issue by Dartanjan** [GeneaLabs/laravel-mixpanel#29]
I set up a clean new project, installed your package and only loaded homepage once. I'm seeing two `Page View` events. Raw data export shows they have identical timestamps:

```
{"event":"Page View","properties":{"time":1484000324,"distinct_id":"2886860801","$browser":"Chrome 55.0.2883.95","Operating System":"OS X 10.11.6","Url":"http://duct.dev/","mp_lib":"php"}}
{"event":"Page View","properties":{"time":1484000324,"distinct_id":"2886860801","$browser":"Chrome 55.0.2883.95","Operating System":"OS X 10.11.6","Url":"http://duct.dev/","mp_lib":"php"}}
```

Can you help? :) I've seen this happen with some of my clients in the past. It seems it's not due to php/laravel or your package, but I'm hoping you've run into this before and have a solution.

**Comment by mikebronner** [comment]
Indeed! :) By any chance, do you have a middleware installed that renders the view before passing it on? This will happen if a view is rendered twice before being passed back to the browser.

**Comment by Dartanjan** [comment]
Hmmm, what I'm doing is a middleware that check whether the user should go through the onboarding sequence. At this point it just redirects to `/welcome` in any case:

``` php
public function handle($request, Closure $next)
{
    return redirect('/welcome');
    
    return $next($request);
}
```

**Comment by mikebronner** [comment]
Comment out the second return, just to make sure and see if it still logs the visit twice?

**Comment by Dartanjan** [comment]
Wow, that was it. Thanks! Any idea how this is possible?

**Comment by mikebronner** [comment]
Good question :)

**Comment by Dartanjan** [comment]
Looking at other routes, I'm starting to think that firing `Page View` on route change may not be ideal. What I assume of `Page View` to represent in my reports, is "User went from A to B". However, routes can be matched more than once in a single request. For example, authenticating with a social login service – receiving the callback (like `yoursite.com/oauth/google/callback`) will count as one page view. Then if you redirect them to a dashboard route, it counts as another page view. This skews metrics for those who care about page views.

Maybe we need some kind of exceptions array, so that certain routes are ignored? Social login callback is a good example – it may also include code/session state and it shouldn't go out to Mixpanel. What do you think?

**Comment by mikebronner** [comment]
Yea, will consider options when revisiting the events that are fired, and perhaps adding additional event listeners on routes or requests, instead of view rendering.
