### ISSUE TITLE
Unable to override consumer and timeouts options

### ISSUE THREAD

**Issue by Dartanjan** [GeneaLabs/laravel-mixpanel#30]
I'm not able to override `consumer`, `connect_timeout` and `timeout` options. They are instantiated in `LaravelMixpanel` but the options themselves are not being taken from `config('services.mixpanel')` where they should probably be in.

My solution for now is to extend the class and pass my own options, but that's not very smooth. Or am I missing something? Readme.md doesn't mention overriding these either.

**Comment by Dartanjan** [comment]
The reason I needed to change these options is because with current setup (socket, 5, 5), I was not getting some events. I tested with curl and much longer timeouts and it worked. This won't be ideal in the long run, but as the app won't see much traffic in the beginning, it's good enough.

**Comment by mikebronner** [comment]
@Dartanjan thank you for reporting this. I will add these options.
