### ISSUE TITLE
Test blade view without script tags, etc.

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-mixpanel#32]

**Comment by richardbenson** [comment]
Using 0.6.4:

Documentation states: `@include('genealabs-laravel-mixpanel::partials.mixpanel')` - putting this in echos out the script file found in `public/genealabs-laravel-mixpanel/mixpanel.js`.  Previously this included script tags so was all that was needed on the page.  Now these need to be wrapped in tags and the documentation updated to reflect that.

It looks like [this change](https://github.com/GeneaLabs/laravel-mixpanel/commit/ca63617d91d7bc34c4a40ec551d9fbc98e5678f7) was the culprit and also removed the script file using the proper init command.

**Comment by mikebronner** [comment]
Yea, 0.6.6 is a temp. patch until I can thoroughly test this. Working on it now.

**Comment by mikebronner** [comment]
This should now be fixed again in 0.6.7. Let me know if you still have issues. Tested auto-tracking and confirmed it working. :)
