### ISSUE TITLE
0.6.8 breaks L5.1 compatibility

### ISSUE THREAD

**Issue by richardbenson** [GeneaLabs/laravel-mixpanel#34]
```
[ErrorException]
  Declaration of GeneaLabs\LaravelMixpanel\Providers\LaravelMixpanelService::boot() should be compatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot(Illuminate\Contracts\Events\Dispatcher $events)
```

You may or may not want to fix this OR just document that L5.1 needs 0.6.7 at most, but then 0.6.7 has it's own issues :/

**Comment by mikebronner** [comment]
@richardbenson Thanks for reporting this! I will try and fix the problem -- should have something within an hour or so for you.

**Comment by mikebronner** [comment]
@richardbenson Could you give dev-master a try on 5.1 for me? From what I have tested it is working, I just want to make sure you will be OK as well.

**Comment by richardbenson** [comment]
@mikebronner thanks for the quick turnaround.

The plugin now doesn't kill Laravel, but events are coming into MP like so `{u'1': {u'Status': u'Logged In'}, u'0': u'Session', u'time': 1497546012}` in the title field.

**Comment by mikebronner** [comment]
@richardbenson yes, I saw that as well. I will have to look why that is happening, perhaps they updated their API. Will open a separate issue for that.
