### ISSUE TITLE
Requirement could not be resolved

### ISSUE THREAD

**Issue by imam** [GeneaLabs/laravel-mixpanel#36]
Hello, I can't install this package. Here is the error log:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-mixpanel ^0.5.3 -> satisfiable by genealabs/laravel-mixpanel[0.5.3].
    - Conclusion: remove laravel/framework v5.4.33
    - Conclusion: don't install laravel/framework v5.4.33
    - genealabs/laravel-mixpanel 0.5.3 requires illuminate/events 5.2.* -> satisfiable by illuminate/events[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/events v5.2.0|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.19|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.21|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.24|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.25|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.26|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.27|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.28|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.31|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.32|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.37|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.43|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.45|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.6|don't install laravel/framework v5.4.33
    - don't install illuminate/events v5.2.7|don't install laravel/framework v5.4.33
    - Installation request for laravel/framework (locked at v5.4.33, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.33].

**Comment by imam** [comment]
I'm using the `dev-master` it works! It's should be updated

**Comment by mikebronner** [comment]
You need to change the version requirements from `genealabs/laravel-mixpanel ^0.5.3` to `genealabs/laravel-mixpanel ^0.6.0`.
