### ISSUE TITLE
Error when I put timestamps to false and save user.

### ISSUE THREAD

**Issue by razvaniacob** [GeneaLabs/laravel-mixpanel#40]
FatalThrowableError in LaravelMixpanelUserObserver.php line 78:
Call to a member function format() on string

**Comment by mikebronner** [comment]
Thanks for reporting this! I will take a look at this over the next few days. :)

**Comment by mikebronner** [comment]
@razvaniacob which version of the package are you using? Please provide the following details:

- Operating system and version
- PHP version
- Development environment stack (i.e. Laravel Homestead)
- Package version

I double-checked the code, and the error referenced above does not appear to correspond to the latest version.

**Comment by razvaniacob** [comment]
OK... I'm using 
Ubuntu 16.04.3 LTS
PHP 7.1.10-1
Laravel 5.3
0.6.0-RC

**Comment by mikebronner** [comment]
Have you tried updating the package to 0.7.0? Let me know how that works for you

**Comment by razvaniacob** [comment]
No.. I'll update it now. I just saw that my version is old. I'll try that and let you know. Thank you!

**Comment by razvaniacob** [comment]
Yes.. it works now with the latest version. Thank you for your help!

**Comment by mikebronner** [comment]
Awesome!
