### ISSUE TITLE
Autotrack don't work

### ISSUE THREAD

**Issue by elamotte** [GeneaLabs/laravel-mixpanel#43]
If I copy paste the new JS snippet from mixpanel I can use the autotrack.

With the include of the package (mixpanel.js) the autotrack don't show up and I have a 404 error in the console.

**Comment by mikebronner** [comment]
Can you provide a screenshot of the console error? When testing this on my end it has worked. Please also provide the following information:

- PHP version:
- Mixpanel for Laravel package version:
- Laravel version:

**Comment by elamotte** [comment]
Sure sorry, wrote the issue quickly this morning. So there it is : 

Php 7.1
laravel-mixpanel 0.7.0
laravel version 5.5

Here's the screenshot : 
https://pasteboard.co/GRYfrru.png

**Comment by mikebronner** [comment]
Hi @elamotte, editor.min.js isn't part of the mixpanel package. That looks like it's something you are including in your app. I wonder if that is preventing further JavaScript from running, which is why mixpanel wouldn't work. Can you try excluding the editor.min.js from your project, and see if it works then? If that's the case, then there seems to be a conflict with between editor.min.js and the mixpanel package, which we would have to investigate more closely.

**Comment by elamotte** [comment]
No actually editor.min.js is an external file, its loaded when you try to launch autotrack from mixpanel :
https://pasteboard.co/GRZ275h.png

So if I don't start the autotrack, it's working but that's my problem it's looks like Autotrack editor don't work with your package.

**Comment by mikebronner** [comment]
OK, let me go over this over the weekend. Thanks for providing the additional details. I will see if I can recreate it. By any chance do you have your code hosted on a public repo? That would be the best, if I can troubleshoot it directly. If not, I'll see if it errors out when I try to do it on my own project.

**Comment by elamotte** [comment]
No actually it's on a private repo. But if I can i'll try to reproduce it simply on a fresh installation tomorrow and share the code with you.

**Comment by elamotte** [comment]
Ok I reproduced it with the same behavior of my private repo : 
https://github.com/elamotte/mixpanel-test/commits/master

You can test it (I can invite you on my mixpanel project as well we'll be easier for you to test).

I finally success to make it works but by disabling your JS snippet and replace it by the official from mixpanel. You can test the autotrack with both method (comment / uncomment the both in the welcome.blade.php header).

Why don't directly use this snippet JS code from mixpanel in your package ? 
It will always go fetch the last mixpanel-2-latest.min.js on mixpanel servers.

**Comment by mikebronner** [comment]
@elamotte thanks for your help. I was able to reproduce the problem and fix the issue. Can you give version 0.7.2 a try and let me know if it works now? Thanks!

**Comment by elamotte** [comment]
@mikebronner thanks, I confirm that It works well.
Thanks a lot for the quick fix, I'll continue with 0.7.2!

**Comment by mikebronner** [comment]
Awesome! Thanks again for letting me know about the issue. Just released 0.7.3 with some refactoring and starting to add unit tests.
