### ISSUE TITLE
Enable-default-tracking value not honored

### ISSUE THREAD

**Issue by chrisrickard** [GeneaLabs/laravel-mixpanel#46]
The setting `services.mixpanel.enable-default-tracking` is not honoured, as even when I st it to false it is still creating the default events.

I believe this is because the classes are still in the `protected $listen` array of your Service.

**Comment by mikebronner** [comment]
@chrisrickard Thanks for reporting this! I will look into this in the near future, time permitting. :)

**Comment by mikebronner** [comment]
@chrisrickard Could you check if version 0.7.5 fixes this issue for you? Thanks for being patient!
