### ISSUE TITLE
array_filter() expects parameter 1 to be array, string given

### ISSUE THREAD

**Issue by SuperIbm** [GeneaLabs/laravel-mixpanel#47]
Laravel 5.6. 
"genealabs/laravel-mixpanel": "^0.7.7",

I allways obtain this error when I try to log in. 

\vendor\genealabs\laravel-mixpanel\src\LaravelMixpanel.php - 50
array_filter() expects parameter 1 to be array, string given
![2018-04-24_01-52-43](https://user-images.githubusercontent.com/10213444/39144076-4b3ca7ba-4762-11e8-92d6-d2ecd9deb49e.png)

**Comment by mikebronner** [comment]
Bugger! Thanks for reporting. I thought I fixed that... will look into it. Sorry for the problem.

**Comment by mikebronner** [comment]
Oh, are you tracking custom events? The recent fixes I did require the properties passed in to track to be an array, not a string.

**Comment by mikebronner** [comment]
Hi @tomstaff thanks for adding some more detail. That is truly strange, because the code in LoginAttempt has been changed to reflect that:

```php
<?php namespace GeneaLabs\LaravelMixpanel\Listeners;

use GeneaLabs\LaravelMixpanel\Events\MixpanelEvent as Mixpanel;

class LaravelMixpanelUserObserver
{
    public function created($user)
    {
        event(new Mixpanel($user, ['User: Registered']));
    }

    public function saving($user)
    {
        event(new Mixpanel($user, ['User: Updated']));
    }

    public function deleting($user)
    {
        event(new Mixpanel($user, ['User: Deactivated']));
    }

    public function restored($user)
    {
        event(new Mixpanel($user, ['User: Reactivated']));
    }
}
```

Are you absolutely sure you updated to the latest version? If you could delete your vendors folder, as well as composer cache, then try running composer update again?

```sh
rm -r vendors
composer clear-cache
composer update
```

**Comment by SuperIbm** [comment]
Maybe you could add some checking like this:

if(!is_array($proporties)) $proporties = [$proporties];

to avoid this error and to be pretty sure that you get correct type of data.
m?

**Comment by SuperIbm** [comment]
```
rm -r vendors
composer clear-cache
composer update
```
A did it but it doesn't still work and I see the same error :(

**Comment by SuperIbm** [comment]
I found why do you have the error. 

There is you have a cycle:
vendor\genealabs\laravel-mixpanel\src\Listeners\MixpanelEvent.php

#23
foreach ($event->trackingData as $eventName => $data) {
                app('mixpanel')->track($eventName, $data);
            }
$event->trackingData - this is your array of data that you pass in the LaravelMixpanel::track($event, $properties = []). In this case you have the array like this:

```
Array
(
    [0] => Login Attempted
)
```

As you understand you cycle your array and pass each index data in LaravelMixpanel::track and after that you have got a string "Login Attempted". And after that you'v got error becose you send the string of index but not the whole array.

**Comment by mikebronner** [comment]
Sorry about the delay. I will try to get this fixed this weekend. :)

**Comment by mikebronner** [comment]
Sorry for this issue -- version 0.7.8 should now be fixed.
