### ISSUE TITLE
Call to undefined function `GeneaLabs\LaravelMixpanel\Http\Requests\timestamp()`

### ISSUE THREAD

**Issue by Djuki** [GeneaLabs/laravel-mixpanel#48]
In the logs we get the error:

`production.ERROR: Call to undefined function GeneaLabs\LaravelMixpanel\Http\Requests\timestamp()`

The undefined function is called in the line:
`vendor/genealabs/laravel-mixpanel/src/Http/Requests/RecordStripeEvent.php:97`

My project is on Laravel5.6 and we do use Cashier for subscribing users.

Where is this function `timestamp` defined?

**Comment by mikebronner** [comment]
Hi @Djuki thanks for reporting this. I will look into this as soon as I am able. If you happen to find the problem in the meanwhile, please feel free to submit a PR with the solution.
