### ISSUE TITLE
Not working on Laravel5.6

### ISSUE THREAD

**Issue by stephenjude** [GeneaLabs/laravel-mixpanel#53]
Nothing is currently working on Laravel 5.6. Looks like the Laravel 5.6 compatible branch has not been merged. How do go about this.

**Comment by mikebronner** [comment]
@stephenjude  You should be able to use the release ... the branch is only for archival purposes, it is currently not up-to-date, sorry about that.

**Comment by stephenjude** [comment]
Finally I was able to use it. My .env mix panel token was configuration was wrong. It work well on Laravel 5.6. Thanks @mikebronner

**Comment by mikebronner** [comment]
@stephenjude Good to hear :) Glad you got it working
