### ISSUE TITLE
IP, browser, etc. is not passed when track is used inside a queued job

### ISSUE THREAD

**Issue by alberthaff** [GeneaLabs/laravel-mixpanel#58]
The properties that are based on the useragent / remote IP are not sent to Mixpanel, when an event is tracked inside a queued job.

**Comment by mikebronner** [comment]
@alberthaff  Thanks for submitting this! Can you verify that 0.8.1 is now working as intended?

**Comment by alberthaff** [comment]
You're welcome. Yes, everything seems to work. 👍
