### ISSUE TITLE
Disable automatic metrics

### ISSUE THREAD

**Issue by fernando-sa** [GeneaLabs/laravel-mixpanel#67]
Hey!

Firstly, thanks for building this amazing package! Secondly, i would like to suggest some parameter to make it easy to stop the automatic metrics, like logins, registrations etc. I have some unique things in my registration process, and would like to deactivate the User registered that come with the package.

Thanks :)

**Comment by mikebronner** [comment]
Hi @fernando-sa, thanks for writing in. Could you provide a bit more detail, and perhaps show the code that you don't want to run? I'm having a hard time visualizing what you intend to do. :) Thanks!

**Comment by fernando-sa** [comment]
I would like some config to disable this part of the package:

![image](https://user-images.githubusercontent.com/23534028/67051531-baaabb00-f111-11e9-9d14-2d13120e87de.png)

I may be missing something, but i couldn't find a good way to disable this "default" trackers

**Comment by mikebronner** [comment]
@fernando-sa  Wouldn't you then just use the barebones library from mix panel? The underlying idea of this package is to automate those events. If you don't want those events, I would recommend simply using the official package from mixpanel. :)

**Comment by fernando-sa** [comment]
That's actually a great point :sweat_smile:. So reformulating, there isn't an easy way to customize those automatic events? E.g: My situation require filters in registration, i would like to add them.

**Comment by mikebronner** [comment]
@fernando-sa could you provide an example filter?

**Comment by fernando-sa** [comment]
I use laravel Auth out of the box system, but with modifications, i have two types of accounts, i would like to tell mixpanel what type was registered, through a filter, instead of just telling that a user registered.

I came to think that maybe this is out of the scope of this package, since the propose is quick integration with laravel auth scaffold.

**Comment by mikebronner** [comment]
Interesting point. So rather than a filter, you really want to pass along additional information about the user. Mixpanel does support custom fields. Let me get back to you on the best way to do this.

**Comment by fernando-sa** [comment]
Yes! I'am calling them filters, because they're used do filter events. The syntax for doing this is just passing an array with the event, like so: 

![image](https://user-images.githubusercontent.com/23534028/67103828-4406cf80-f19c-11e9-9dbc-eb0061f1001e.png)

Maybe a configuration file for this is just too much complexity, but if i could publish the files that are being called to register those automatic events, i could personalize them. I'm still learning about package development, so i don't know if publishing files have this purpose in mind.

**Comment by mikebronner** [comment]
Could you give release 0.9.1 a try and let me know how it goes? It should be doable now. Check the readme for instructions.

**Comment by fernando-sa** [comment]
Hey! Thank you for the quick responses, and quick change in the package. I had to start using the basic mixpanel library, since i was falling behind schedule. I read the README, and found it a bit confusing, i went to the commits history to understand how this new "feature" works. Maybe adding an real life example would be great for the next ones who come across this package.

Thank you again for your proactivity and quickness in solving this issue. Situations like this inspire me to be a better developer, and to return some work to the community :smile:
