### ISSUE TITLE
How to add custom fields to people data

### ISSUE THREAD

**Issue by zenichanin** [GeneaLabs/laravel-mixpanel#68]
I'm trying to add phone number and certain other fields to default people data such as when user logs in and other places specified in readme. What's the easiest way of doing that?

**Comment by mikebronner** [comment]
Hi @zenichanin, thanks for writing in. You should be able to do this easily by following the instructions in the usage section of the readme: https://github.com/GeneaLabs/laravel-mixpanel#usage

You could achieve this by setting up a new middleware where you set the user's information with something like the following code:
```php
$mixPanel = app('mixpanel');
$mixPanel->people->set($user->id, [
    "phone" => "(800)555-1212",
]);
```

Hope this helps!
