### ISSUE TITLE
Error on Laravel 5.6

### ISSUE THREAD

**Issue by lmatab** [GeneaLabs/laravel-mixpanel#75]
Hi, Thanks for sharing this package.

I am getting this error when trying to install it on Laravel 5.6

Problem 1
    - Installation request for genealabs/laravel-mixpanel ^0.10.1 -> satisfiable by genealabs/laravel-mixpanel[0.10.1].
    - Conclusion: remove laravel/framework v5.6.37
    - Conclusion: don't install laravel/framework v5.6.37
    - genealabs/laravel-mixpanel 0.10.1 requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2].
    - don't install illuminate/queue v7.0.0|don't install laravel/framework v5.6.37
    - don't install illuminate/queue v7.0.1|don't install laravel/framework v5.6.37

Any thoughts?

**Comment by mikebronner** [comment]
Hi @lmatab, this package requires Laravel 7. You are free to fork it and make any necessary changes to get it to run on Laravel 5.6, but we are unable to support that. Best of luck! :)
