### ISSUE TITLE
genealabs/laravel-mixpanel 0.10.1 requires illuminate/config ^7.0

### ISSUE THREAD

**Issue by aakarim** [GeneaLabs/laravel-mixpanel#76]
Great package.

My setup is still at Laravel 6.x and I'm getting an error on upgrade to 0.10.1 that's asking me to upgrade to Laravel 7.x, which I'm not ready for yet. Is this dependency necessary? Perhaps it could run Laravel 7.x specific integrations on a different branch?

I'm happy to contribute if needs be.

**Comment by mikebronner** [comment]
HI @aakarim, please feel free to fork the package and make any adjustments you need to get it to run on old versions of Laravel. At this time I am only going to be supporting the current version of Laravel.
