### ISSUE TITLE
How do I remove auto User Updated?

### ISSUE THREAD

**Issue by trisle** [GeneaLabs/laravel-mixpanel#77]
Hi there,

I'm on Laravel 5.4. I'm wondering why my users keep getting User Updated (repeated many times) out of nowhere – when signing in, logging out, performing some random actions... and it keeps repeating.

https://i.imgur.com/4gpFjxZ.png

How do I remove the auto tracking for User Updated? Or, what really triggered this?

Thank you :)

**Comment by mikebronner** [comment]
Hi @trisle, thanks for writing in! My guess is that there is a bug somewhere, not sure if its this package or not. However, Laravel 5.4 hasn't been supported for a LONG time, so you won't be getting the latest version of the package, that included a lot of bug fixes.

**Comment by mikebronner** [comment]
Please feel free to respond, I'm just closing this issue now, as we will not be going back and updating previous versions.

**Comment by trisle** [comment]
Bugga, I'm on a system that can't be upgraded anytime soon.
Was wondering if it's possible to ask you a favor for a check? In return I can gift you a free activity on vibeji.com (good for the lock-down period these days) :)

**Comment by trisle** [comment]
Ah sorry you beat me by a few secs. No worries :)

**Comment by mikebronner** [comment]
Sorry about that. Good luck!

**Comment by trisle** [comment]
Thank you, just one last question.

I tried disabling the auto-tracking in services.php but seems like it's not tracking anymore?

```
'mixpanel' => [
        'enable-default-tracking' => false
    ]
```

**Comment by mikebronner** [comment]
Yes, that turns all the automated tracking off. It is meant for those times where you have manual tracking.
