### ISSUE TITLE
Configurable Host Endpoint

### ISSUE THREAD

**Issue by designvoid** [GeneaLabs/laravel-mixpanel#79]
Hi there,

It appears there is now a need to be able to switch the api host for EU accounts - the host is now `api-eu.mixpanel.com`

I have got around this for now by doing the following in my AppServiceProvider

```
        $this->app->bind(LaravelMixpanel::class, function ($app) {
            return new LaravelMixPanel($app->request, [
                'host' => 'api-eu.mixpanel.com'
            ]);
        });
        $this->app->singleton('mixpanel', function ($app) {
            return Mixpanel::getInstance(Config::get('services.mixpanel.token'), [
                'host' => 'api-eu.mixpanel.com'
            ]);
        });
```

Not sure if this for the best or wether maybe I should submit a PR to enable setting the host in the services file?

In addition, whilst diving through the code to see how things are working I noticed that I could just fire a new `Mixpannel` event to track custom events:

```
            event(new Mixpanel(Auth::user(), ['Applicant Feedback Left' => []]));
```

Which is obviously different to the method described in the readme - am I missing something fundamental or is this an intended option? 

Cheers!!

**Comment by mikebronner** [comment]
Hi @designvoid, thanks for bringing this up! I think it would be good to add the host to the config options. I will have to look into the docs about tracking custom events. Chances are good that it is a hold-over from prior functionality. Any PRs you can create would be awesome, it would definitely speed things up.

**Comment by designvoid** [comment]
Hi @mikebronner I have submitted a PR but there seems to be some issues with the CI pipeline?

**Comment by mikebronner** [comment]
@designvoid Thanks! I'll take a look later today, time permitting. :) No worries about the CI stuff.

**Comment by mikebronner** [comment]
I'll be looking at this now ... sorry for the delay, yesterday turned into chaos.

**Comment by mikebronner** [comment]
@designvoid Can you try release 0.10.3 and let me know how that works for you? Thanks again for taking care of this!!! I will work on the CI another time, it has to be reworked from the ground up.
