### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by wassim** [GeneaLabs/laravel-mixpanel#84]
Is it possible to add support for Laravel 8?

```
composer require genealabs/laravel-mixpanel

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-mixpanel ^0.10.3 -> satisfiable by genealabs/laravel-mixpanel[0.10.3].
    - Conclusion: remove laravel/framework v8.13.0
    - Conclusion: don't install laravel/framework v8.13.0
```

**Comment by mikebronner** [comment]
@wassim Sorry about that, missed this one. Will upgrade in a bit.

**Comment by mikebronner** [comment]
@wassim Please try release 0.11.0 or greater. Let me know how it works. I made the necessary changes, but will need to rewrite the tests. I wanted to get this out to you as soon as possible.

**Comment by wassim** [comment]
@mikebronner works fine now. Thanks for fixing this asap, also thank you for making this package, haven't tried it yet but will give thoughts once I do.
