### ISSUE TITLE
Problems to install your package

### ISSUE THREAD

**Issue by pixsolution** [GeneaLabs/laravel-mixpanel#88]
Hi! I tried to install your package but show me this error
![image (1)](https://user-images.githubusercontent.com/47191848/103629322-738c2e00-4f40-11eb-92d3-53641e1bee80.png)
why is that? I'm using laravel 7.

Regards

**Comment by mikebronner** [comment]
We only support the latest Laravel version. Feel free to make your own fork and any necessary changes to support older versions.

**Comment by nakarimi** [comment]
@mikebronner so may its better to update Requirements and Compatibility as you mentioned it is supporting Laravel >= 7.0 but doesn't, so others will know what is the proper version.

**Comment by mikebronner** [comment]
@nakarimi Thanks for the documentation issue, will get that updated ASAP.
